name: build_and_formatting

on:
    push:
        branches: ["task/6_addCI"]
    pull_request:
        branches: ["master", "dev"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: '8.0.x'

        - name: Install EF Core Tools
          run: dotnet tool install --global dotnet-ef --version 9.0.11

        - name: Restore dependencies
          run: dotnet restore

        - name: Build application
          run: dotnet build --no-restore

        - name: Run database migrations
          run: dotnet ef database update --project Filmatch

        - name: Formatting
          run: dotnet format --verify-no-changes  
          
